// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview AI Slogan Generation flow for YES ACADEMY.
 *
 * - generateSlogan - A function that generates slogans based on keywords.
 * - SloganInput - The input type for the generateSlogan function.
 * - SloganOutput - The return type for the generateSlogan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SloganInputSchema = z.object({
  keywords: z
    .string()
    .describe(
      'Comma-separated keywords that represent the brand essence or desired message of the slogan.'
    ),
});
export type SloganInput = z.infer<typeof SloganInputSchema>;

const SloganOutputSchema = z.object({
  slogan: z
    .string()
    .describe('An inspirational and catchy slogan for YES ACADEMY.'),
});
export type SloganOutput = z.infer<typeof SloganOutputSchema>;

export async function generateSlogan(input: SloganInput): Promise<SloganOutput> {
  return generateSloganFlow(input);
}

const sloganPrompt = ai.definePrompt({
  name: 'sloganPrompt',
  input: {schema: SloganInputSchema},
  output: {schema: SloganOutputSchema},
  prompt: `You are a marketing expert tasked with creating a slogan for YES ACADEMY, a premium multisport academy based in China with an extension to Vietnam.

  The slogan should be modern, dynamic, premium, and inspiring, reflecting the academy's brand identity.
  The slogan must capture the essence of the brand using these keywords: {{{keywords}}}.

  Generate one highly creative and impactful slogan.
  `,
});

const generateSloganFlow = ai.defineFlow(
  {
    name: 'generateSloganFlow',
    inputSchema: SloganInputSchema,
    outputSchema: SloganOutputSchema,
  },
  async input => {
    const {output} = await sloganPrompt(input);
    return output!;
  }
);
